# Workflow to build and push a Docker image to Docker Hub, GitHub and Quay Container Registries
name: Build fb-exporter-cable

# Controls when the action will run
on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  schedule:
    - cron: '0 0 1 * *'  # runs at 00:00 on the first day of every month
  push:
    branches: main

# Environment variables available to all jobs and steps in this workflow
env:
  DOCKER_BUILDKIT: 1
  DOCKER_NAME: fb-exporter-cable
  DOCKER_DESCRIPTION: "Fritzbox Exporter for Prometheus - Cable Version"

# Jobs to run once the workflow is triggered
jobs:
  # Job to get image and repository details
  metadata:
    name: Get image and repository details
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      labels: ${{ steps.metadata.outputs.labels }}
      tags: ${{ steps.metadata.outputs.tags }}
      platforms: linux/amd64
      #,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Generate image metadata with Caddy version
        uses: docker/metadata-action@v5.8.0
        id: metadata
        with:
          images: |
            docker.io/${{ github.actor }}/${{ env.DOCKER_NAME }}
            ghcr.io/${{ github.actor }}/${{ env.DOCKER_NAME }}
#            quay.io/${{ github.actor }}/${{ env.DOCKER_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.DOCKER_NAME }}
            org.opencontainers.image.description=${{ env.DOCKER_DESCRIPTION }}

  # Job to build and publish Docker image
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    needs: metadata

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Repository
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and publish container image
        uses: docker/build-push-action@v6.18.0
        id: build
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          labels: ${{ needs.metadata.outputs.labels }}
          platforms: ${{ needs.metadata.outputs.platforms }}
